version: "3.3"
services:

  nisum_users:
    build:
      context: .

    environment:
      - JWT_KEY=AvTPEJRwCxnqApQGkuWsl-iUafNAHQAwTIJM8hdV4Oo
      - EXPIRATION_TIME=65000
      - LADA_KEY_PATTERN=^[0-9]{2}$$

    ports:
      - "8080:8080"


