
spring:
  datasource:
    url: jdbc:h2:mem:nisum_users
    username: sa
    password: 12345
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
  h2:
    console.enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

users:
  ladakey_pattern: ${LADA_KEY_PATTERN:^[0-9]{2}$}
  JWT_KEY: ${LADA_KEY_PATTERN:AvTPEJRwCxnqApQGkuWsl-iUafNAHQAwTIJM8hdV4Oo}
  EXPIRATION_TIME: ${LADA_KEY_PATTERN:64000}